### ISSUE TITLE
Graphic Design Contribution

### ISSUE THREAD

**Issue by nunojesus** [utunga/boxlog#1]
Hi, I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by utunga** [comment]
@nunojesus what a kind offer!  We may take you up on this! 

One thing. It certainly is our intention to release most of our source code in the open but there is also a hardware componenet that we were hoping to kickstarter etc. Do you know anything about this project? Still a bunch of stuff going on behind the scenes but this gives some idea http://dramabox.webflow.io/

**Comment by nunojesus** [comment]
I read the project it´s really a good idea, the name is Boxlog, or Trackbox? Do you have any special request for the logo? like shapes? colors? etc.

Greetings
